#ifndef __MAIN_H__
#define __MAIN_H__

// pluse output: 100ms cycle, 100us high level
#define SENSOR_OUT1			GPIO_NUM_5
#define SENSOR_OUT5			GPIO_NUM_32 // RTC_GPIO9
#define SENSOR_OUT7			GPIO_NUM_14	// RTC_GPIO16
#define SENSOR_OUT10		GPIO_NUM_25 // RTC_GPIO6

// sensor status input: high level effect
#define SENSOR_OUT2			GPIO_NUM_18
#define SENSOR_OUT3			GPIO_NUM_19
#define SENSOR_OUT4			GPIO_NUM_35 // RTC_GPIO5
#define SENSOR_OUT6			GPIO_NUM_33
#define SENSOR_OUT8			GPIO_NUM_12 // RTC_GPIO15
#define SENSOR_OUT9			GPIO_NUM_13
#define SENSOR_OUT11		GPIO_NUM_26 // RTC_GPIO7
#define SENSOR_OUT12		GPIO_NUM_27

#define SENSOR_OUT1_SEL			(1ULL<<SENSOR_OUT1)
#define SENSOR_OUT2_SEL			(1ULL<<SENSOR_OUT2)
#define SENSOR_OUT3_SEL			(1ULL<<SENSOR_OUT3)
#define SENSOR_OUT4_SEL			((uint64_t)((uint64_t)1<<SENSOR_OUT4))
#define SENSOR_OUT5_SEL			((uint64_t)((uint64_t)1<<SENSOR_OUT5))
#define SENSOR_OUT6_SEL			((uint64_t)((uint64_t)1<<SENSOR_OUT6))
#define SENSOR_OUT7_SEL			(1ULL<<SENSOR_OUT7)
#define SENSOR_OUT8_SEL			(1ULL<<SENSOR_OUT8)
#define SENSOR_OUT9_SEL			(1ULL<<SENSOR_OUT9)
#define SENSOR_OUT10_SEL		(1ULL<<SENSOR_OUT10)
#define SENSOR_OUT11_SEL		(1ULL<<SENSOR_OUT11)
#define SENSOR_OUT12_SEL		(1ULL<<SENSOR_OUT12)

#define SENSOR_SEL_ALL		((uint64_t)(SENSOR_OUT8_SEL|SENSOR_OUT11_SEL|SENSOR_OUT4_SEL))
#define SENSOR_SEL_PLUSE	((uint64_t)(SENSOR_OUT7_SEL|SENSOR_OUT10_SEL|SENSOR_OUT5_SEL))

#define SENSOR_POWER		GPIO_NUM_15 // RTC_GPIO13
#define SENSOR_POWER_SEL	(1ULL<<SENSOR_POWER)

#define SENSOR_LED			GPIO_NUM_22
#define SENSOR_LED_SEL		(1ULL<<SENSOR_LED)

//#define ESP_WIFI_SSID		"HUAWEI-ESPWIFI"
//#define ESP_WIFI_SSID		"TP-LINK_4684"
#define ESP_WIFI_SSID		"Robot-inside"
#define ESP_WIFI_PASS		"bgy2018@"
//#define MODBUS_TCP_SERVER		"192.168.203.160"
#define MODBUS_TCP_SERVER		"10.110.30.106"
//#define MODBUS_TCP_SERVER		"192.168.1.100"
//#define MODBUS_TCP_SERVER		"10.187.64.59"
//#define MODBUS_TCP_SERVER		"192.168.3.21"
#define MODBUS_TCP_PORT			502
#define MODBUS_SERVER_ID		0x08
#define MODBUS_SENSOR_ADDR		0x0FA6
#define MODBUS_VOLTAGE_ADDR		0x0FA7

#ifndef BIT
#define BIT(x) (1 << (x))
#endif

#include "config_task.h"
extern esp_conf_t system_config;

#endif
